#!/usr/bin/env bash
# this script installs nginx as webserver on ubuntu machine

# install nginx
sudo apt-get -y update 
sudo apt-get -y install nginx

# allow firewall connection on HTTP Port 80
ufw allow 'Nginx HTTP'

# to grant permission on nginx while inside your server
sudo chown -R "$USER":"$USER" /var/www && sudo chmod -R 755 /var/www

# create index.html to be used at root
echo "Hello World!" > index.html

# move the index.html to root folder
mv index.html /var/www/html

# append redirection after server_name line
re_direction="\\\trewrite ^/redirect_me https://www.github.com/Nwaigba66 permanent;"
sudo sed -i "/listen 80 default_server/a $re_direction" /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart
