#!/usr/bin/env bash
# this script installs nginx as webserver on ubuntu machine

# install nginx
sudo apt-get -y update 
sudo apt-get -y install nginx

# allow firewall connection on HTTP Port 80
ufw allow 'Nginx HTTP'

# to grant permission on nginx while inside your server
sudo chown -R "$USER":"$USER" /var/www && sudo chmod -R 755 /var/www

# create index.html to be used at root
echo "Hello World!" > index.html

# move the index.html to root folder
mv index.html /var/www/html

# append redirection after server_name line
re_direction="\\\trewrite ^/redirect_me https://www.github.com/Nwaigba66 permanent;"
sudo sed -i "/listen 80 default_server/a $re_direction" /etc/nginx/sites-available/default

# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
echo "Ceci n'est pas une page" > /var/www/html/custom404.html 

if ! grep -q "error_page 404 /404.html;" "$nginx_config"; then sudo sed -i "/server_name _;/a \\
	\\error_page 404 /404.html;\\location /404.html {\\root /var/www/html;\\}" "$nginx_config"
fi

# append redirection after server_name line
if ! grep -q "location /redirect_me {" "$nginx_config"; then
       sudo sed -i "/server_name _;/a \\
	\\
	location /redirect_me {\\
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\
	}" "$nginx_config"
fi

# restart nginx
sudo service nginx restart
