#!/usr/bin/env bash
# this script installs nginx as webserver on ubuntu machine

# install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# allow firewall connection on HTTP Port 80
ufw allow 'Nginx HTTP'

# to grant permission on nginx while inside your server
sudo chown -R "$USER":"$USER" /var/www && sudo chmod -R 755 /var/www

# create index.html to be used at root
echo "Hello World!" > /var/www/html/index.html


# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# append redirection after server_name line
printf %s "server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;
    index  index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.github.com/Nwaigba66;
    }
    error_page 404 /404.html;
        location = /404.html {
            root /var/www/html/;
            internal;
        }
}" > /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
