#!/usr/bin/env bash
#Configures a ufw firewall on ports 22, 80, 443 and denies other incoming traffic
sudo apt-get update
sudo apt-get install ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
